[package]
name = "elm-magic-macros"
version = "0.8.5"
edition = "2021"
description = "Procedural macros for elm-magic: #[view], ui!"
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/jaywoo0830a/elm"
keywords = ["ui", "gui", "jsx", "elm", "macros"]
categories = ["gui", "rust-patterns"]

[lib]
proc-macro = true

[dependencies]
